#!/bin/bash

buffer="/etc/.backlight_deamon"
actual="/sys/class/backlight/intel_backlight/brightness"

sudo rm -r $buffer
sudo mkdir $buffer
sudo chmod 777 $buffer

repeat() {
    while ((1));
    do
        active_pid=`xdotool getactivewindow getwindowpid`
        if [ -f $buffer/$active_pid ]
        then
            sudo cat $buffer/$active_pid > $actual
        fi

        sleep 0.1
        
    done
}

repeat &

