#!/bin/bash

buffer="$HOME/.backlight_deamon"
actual="/sys/class/backlight/intel_backlight/brightness"

repeat() {
    while ((1));
    do
        sudo cat $buffer > $actual
        sleep 0.2
    done
}

repeat &

