#!/bin/bash


SCALE=5


draw() {
    color="38;5;$1m"

    while ((1))
    do
        lines=`tput lines`
        cols=`tput cols`
        len=$(( (100 - RANDOM % 100) * (100 - RANDOM % 100) * (100 - RANDOM % 100) * (100 - RANDOM % 100) * (100 - RANDOM % 100) % SCALE + 1 + (256 - $1) / 240 ))
        x=$((RANDOM % ($lines / $len) * $len + 1))
        y=$((RANDOM % ($cols / ($len * 2)) * ($len * 2) + 1))
        c=`echo $(($RANDOM % 19 + 41)) | xxd -p -r`
        for ((i=0;i<$len;i++))
        do
            for ((j=0;j<$len;j++))
            do
                printf "\e[0m\e[$((x + i));$((y + (j * 2)))H\e[${color}${c}${c}"
            done
        done

        sleep $2
    done
}


# clean
printf "\e[0m\e[2J"


ratio_bw=1
for ((i=0;i<$ratio_bw;i++))
do
    for ((i=232;i<253;i++))
    do
        sleep "0.$(($RANDOM % 500))"
        draw $i 0.05 &
    done
done


ratio_color=1
for ((i=0;i<$ratio_color;i++))
do
    for ((i=0;i<16;i++))
    do
        sleep "0.$(($RANDOM % 500))"
        draw $i 0.2 &
    done
done


trap "trap - SIGTERM && kill -- -$$" SIGINT SIGTERM EXIT
wait

