#!/bin/bash

SCALE=5
DELAY=0.01

draw() {
    color="48;5;$1m"
    while ((1))
    do
        lines=`tput lines`
        cols=`tput cols`

        len=$(( (100 - RANDOM % 100) * (100 - RANDOM % 100) * (100 - RANDOM % 100) * (100 - RANDOM % 100) * (100 - RANDOM % 100) % SCALE + 1 + (256 - $1) / 240 ))
        x=$((RANDOM % ($lines / $len) * $len + 1))
        y=$((RANDOM % ($cols / ($len * 2)) * ($len * 2) + 1))

        for ((i=0;i<$len;i++))
        do
            for ((j=0;j<$len;j++))
            do
                printf "\e[0m\e[$((x + i));$((y + (j * 2)))H\e[$color  "
            done
        done

        if [ $1 -ge 0 ] && [ $1 -lt 16 ]
        then
            sleep `bc -l <<< "scale=2; $DELAY * $SCALE * $SCALE"`
        else
            sleep $DELAY
        fi
    done
}

clean() {
    while ((1))
    do
        printf "\e[0m\e[2J"
        sleep $DELAY
    done
}

# clean &
printf "\e[0m\e[2J"

for ((i=232;i<256;i++))
do
    sleep `bc -l <<< "scale=3; ($RANDOM % 100) / 1000"`
    draw $i &
done
for ((i=0;i<16;i++))
do
    sleep `bc -l <<< "scale=3; ($RANDOM % 100) / 1000"`
    draw $i &
done

trap "trap - SIGTERM && kill -- -$$" SIGINT SIGTERM EXIT

wait
