#!/bin/bash


##############################
##############################

config_file="$HOME/.occ_data"

##############################
##############################

grep_awk() {
    gal=`grep -i $1 $config_file | awk '{print $2}'`
}

connect() {
    disconnect

    grep_awk "domain";   domain=$gal
    grep_awk "username"; username=$gal
    grep_awk "password"; password=$gal
    echo $password | sudo openconnect -b $1.$domain -u $username
}


disconnect () {
	sudo pkill -SIGINT openconnect
}


help() {
    echo "occ uses openconnect to connect and disconnect :)"
    echo "    usage:"
    echo "        occ <server-prefix>    connects to vpn server at server-prefix.vpn_server-postfix"
    echo "        occ d                  disconnects!"
    echo "        occ -h|--help          shows this help"
    echo 
    echo "    ALSO CONSIDER writing your vpn data in $config_file following this format:"
    echo "        domain:   <vpn_server_postfix>"
    echo "        username: <username>"
    echo "        password: <password>"
    exit 0
}


if (($# == 0)); then
    help
fi

case $1 in
	d )
	disconnect
	;;
	-h|--help)
    help
    ;;
    *)
	connect $1
	;;
esac

