#!/bin/bash


brightness_file="/sys/class/backlight/intel_backlight/brightness"
max_brightness=`cat /sys/class/backlight/intel_backlight/max_brightness`


get_current_brightness() {
    brightness=`cat $brightness_file`
}


bright() {
    sudo echo $1 > $brightness_file
}


if [[ $1 =~ [+-]{0,1}[0-9]+ ]]
then
    get_current_brightness
    change=`echo $1 | tr -d +`
    expected_brightness=`bc -l <<< "scale=0; $brightness + $change * $max_brightness / 100"`
    if [ "$expected_brightness" -ge "$max_brightness" ]
    then
        bright $max_brightness
    elif [ "$expected_brightness" -le "0" ]
    then
        bright "0"
    else
        bright $expected_brightness
    fi
    get_current_brightness
    echo `bc -l <<< "scale=0; $brightness * 100 / $max_brightness"`%
else
    echo "usage:"
    echo
    echo "x c    changes screen backlight by c percentage"
fi

